### ISSUE TITLE
isLeft and isRight should be documented

### ISSUE THREAD

**Issue by dotnetCarpenter** [sanctuary-js/sanctuary-either#41]
[`Either.isLeft`](https://github.com/sanctuary-js/sanctuary/blob/v3.1.0/index.js#L2305) and [`Either.isRight`](https://github.com/sanctuary-js/sanctuary/blob/v3.1.0/index.js#L2325) are part of the public facing API but is not documented in the README.

**Comment by davidchambers** [comment]
Another option is to provide and document the case-folding function:

```haskell
either :: (a -> c) -> (b -> c) -> Either a b -> c
```

What do you think of this idea, @dotnetCarpenter?

**Comment by dotnetCarpenter** [comment]
@davidchambers Is that because you dislike Either.isLeft and Either.isRight?

Since js does not have pattern matching, both properties are extremely useful. I keep wishing fluture had something akin.

I used both a lot while developing PR#308 in sanctuary-def (not sure they are gonna stay in the finished PR though).
See [line 1542](https://github.com/sanctuary-js/sanctuary-def/pull/308/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R1542) and [line 1571](https://github.com/sanctuary-js/sanctuary-def/pull/308/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R1542)

**Comment by davidchambers** [comment]
I prefer the case-folding function because it does not expose implementation details.

Here is a function-based implementation that can provide `either` but not `isLeft` and `isRight` properties:

```javascript
//    Left :: a -> Either a b
const Left = a => left => right => left (a);

//    Right :: b -> Either a b
const Right = b => left => right => right (b);

//    either :: (a -> c) -> (b -> c) -> Either a b -> c
const either = f => g => e => e (f) (g);

//    showEither :: (Showable a, Showable b) => Either a b -> String
const showEither = either (a => 'Left (' + show (a) + ')')
                          (b => 'Right (' + show (b) + ')');
```

`isLeft :: Either a b -> Boolean` and `isRight :: Either a b -> Boolean` can be defined in terms of `either`. :)
